language: android

jdk:
  - oraclejdk8

branches:
  only:
    - master
    
script: "./gradlew clean assembleDebug"

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25  
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
sudo: false
